version: '3'

services:
  db:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=manisha
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=testdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
#  web:
#    build: .
#    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
